### ISSUE TITLE
需要更新，获取验证码失败，原因为version not right

### ISSUE THREAD

**Issue by sankuka** [6DDUU6/SchoolAuthentication#10]
![屏幕截图 2024-03-27 095241](https://github.com/6DDUU6/SchoolAuthentication/assets/30693953/10514f25-249e-4a3d-869f-ad9106b66443)

**Comment by 6DDUU6** [comment]
我看了下，是验证码接口获取不到验证码了，导致的无法登录。
程序的登录接口其实是旧的接口，可能最近更新被砍掉了？

**Comment by sankuka** [comment]
可能是吧，21年那会好像登录接口也动过，那暂时没办法了

**Comment by 6DDUU6** [comment]
> 可能是吧，21年那会好像登录接口也动过，那暂时没办法了

可以邮箱发我一个最新版app我看看

**Comment by 6DDUU6** [comment]
现在缺一个会抓http包的（）

**Comment by 6DDUU6** [comment]
应该没办法了，推荐搭建去用新的项目：
https://github.com/Rsplwe/ESurfingDialer
